// src/icons.ts
//
// The app's soft clay icons, by name: the first few drawn for streaks and the carrot
// currency (assets/emojis), Bonbon himself, and the rest made to match (assets/icons). Used
// wherever an emoji stood in as an icon; emojis in sentences, notifications and Bonbon's
// messages stay as text, as do the ones people pick for their own categories and jars.

export const ICONS = {
  fire:            require('../assets/emojis/Fire.png'),
  star:            require('../assets/emojis/Star.png'),
  carrot:          require('../assets/emojis/carrot.png'),
  bonbon:          require('../assets/bonbon/idle.png'),
  'bar-chart':     require('../assets/icons/bar-chart.png'),
  barbell:         require('../assets/icons/barbell.png'),
  basket:          require('../assets/icons/basket.png'),
  bell:            require('../assets/icons/bell.png'),
  box:             require('../assets/icons/box.png'),
  brain:           require('../assets/icons/brain.png'),
  burger:          require('../assets/icons/burger.png'),
  bus:             require('../assets/icons/bus.png'),
  calendar:        require('../assets/icons/calendar.png'),
  'chart-up':      require('../assets/icons/chart-up.png'),
  check:           require('../assets/icons/check.png'),
  chick:           require('../assets/icons/chick.png'),
  clipboard:       require('../assets/icons/clipboard.png'),
  cloud:           require('../assets/icons/cloud.png'),
  coffee:          require('../assets/icons/coffee.png'),
  coin:            require('../assets/icons/coin.png'),
  crown:           require('../assets/icons/crown.png'),
  document:        require('../assets/icons/document.png'),
  download:        require('../assets/icons/download.png'),
  dumbbell:        require('../assets/icons/dumbbell.png'),
  envelope:        require('../assets/icons/envelope.png'),
  'flexed-arm':    require('../assets/icons/flexed-arm.png'),
  folders:         require('../assets/icons/folders.png'),
  gear:            require('../assets/icons/gear.png'),
  'green-heart':   require('../assets/icons/green-heart.png'),
  'id-card':       require('../assets/icons/id-card.png'),
  jar:             require('../assets/icons/jar.png'),
  letters:         require('../assets/icons/letters.png'),
  lightbulb:       require('../assets/icons/lightbulb.png'),
  lightning:       require('../assets/icons/lightning.png'),
  medal:           require('../assets/icons/medal.png'),
  mirror:          require('../assets/icons/mirror.png'),
  'money-bag':     require('../assets/icons/money-bag.png'),
  'money-wings':   require('../assets/icons/money-wings.png'),
  moon:            require('../assets/icons/moon.png'),
  notebook:        require('../assets/icons/notebook.png'),
  padlock:         require('../assets/icons/padlock.png'),
  palette:         require('../assets/icons/palette.png'),
  'party-popper':  require('../assets/icons/party-popper.png'),
  'piggy-bank':    require('../assets/icons/piggy-bank.png'),
  pill:            require('../assets/icons/pill.png'),
  'rain-cloud':    require('../assets/icons/rain-cloud.png'),
  receipt:         require('../assets/icons/receipt.png'),
  refresh:         require('../assets/icons/refresh.png'),
  scroll:          require('../assets/icons/scroll.png'),
  seedling:        require('../assets/icons/seedling.png'),
  'shopping-bags': require('../assets/icons/shopping-bags.png'),
  sparkles:        require('../assets/icons/sparkles.png'),
  'star-glow':     require('../assets/icons/star-glow.png'),
  stopwatch:       require('../assets/icons/stopwatch.png'),
  tag:             require('../assets/icons/tag.png'),
  target:          require('../assets/icons/target.png'),
  trash:           require('../assets/icons/trash.png'),
  trophy:          require('../assets/icons/trophy.png'),
  upload:          require('../assets/icons/upload.png'),
  wave:            require('../assets/icons/wave.png'),
} as const;

export type IconName = keyof typeof ICONS;
